### ISSUE TITLE
pcilib: sysfs_read_vpd: read failed: Input/output error

### ISSUE THREAD

**Issue by caravena** [pciutils/pciutils#12]
Hello,

Open bug in launchpad.net
https://bugs.launchpad.net/bugs/1791309

In console:
```
# lspci -vvnn > a.txt
pcilib: sysfs_read_vpd: read failed: Input/output error
```
Best regards,
--
Cristian Aravena Romero (caravena)

**Comment by gollux** [comment]
What device are you trying to dump? What does lspci print before it dies?

**Comment by caravena** [comment]
I close this report ... It does not happen after my updates...

**Comment by xiaoheise** [comment]
what did you updated, kernel or pci.ids? what is the root cause
