### ISSUE TITLE
Config space write in Windows not working

### ISSUE THREAD

**Issue by Johannes4Linux** [pciutils/pciutils#126]
Hello,

I want to write to the PCIe config space in Windows but it is not working.

I compiled the pciutils on Windows 10 64Bit with cygwin and mingw. Here is my make command:

````
make CROSS_COMPILE=x86_64-w64-mingw32- HOST=x86_64-windows ZLIB=no IDSDIR="" -j 8
````

On the access methods only *win32-cfgmgr32* works. Reading from the config space also works:

```
$ ./setpci.exe -s 05:00.0 10.l
pcilib: Cannot retrieve resource data of PCI device PCI\VEN_11F8&DEV_8531&SUBSYS_11F80000&REV_00\4&296156d4&0&00E8: Empty data.
[some more empty data warnings, but they don't match the VID/DID of my PCIe Device]
aa300000
```

Now I want to write to this register (I know, this is BAR0, but my PCIe card is not used by any driver or any program):

```
$ ./setpci.exe -s 05:00.0 10.l=0x12345678
pcilib: Cannot retrieve resource data of PCI device PCI\VEN_11F8&DEV_8531&SUBSYS_11F80000&REV_00\4&296156d4&0&00E8: Empty data.
[some more empty data warnings, but they don't match the VID/DID of my PCIe Device]
```

But when I read it back again, it is still the old value. If I do this with the pciutils from https://eternallybored.org/misc/pciutils/ reading and writing works. I know, this version uses a driver (DirectIO) to access the config space.

Is it possible to write to the config space from Windows with pciutils? I am quite sure it is possible and the error is on my side. So, do I have to change anything with the compilation or do I have to add another access method? Do I have to change  or enable anything on windows to make it work?

**Comment by pali** [comment]
win32-cfgmgr32 access method does not provide access to the PCI config space as this is limitation of windows cfgmgr32 API. You need to use other access method for PCI config space. win32-cfgmgr32 provides just "fake" read-only 64-byte long PCI config space with some synthetic values deduced from cfgmgr32 API.
