### ISSUE TITLE
Current hex parser doesn't support 0x prefixes for hex numbers

### ISSUE THREAD

**Issue by richfifeg** [pciutils/pciutils#132]
This, for instance, worked fine in 3.7.0:

```
lspci -vvv -d 0x8086:0x2018
```

but breaks with "Invalid Vendor ID" in 3.9.0.  I get that 'x' was repurposed to "match anything", but that is not supported in -d queries anyway and this is breaking scripts left and right.

A patch would be something to effect of:

```
diff --git a/lib/filter.c b/lib/filter.c
index 7038451..2f6c1c2 100644
--- a/lib/filter.c
+++ b/lib/filter.c
@@ -76,6 +76,9 @@ parse_hex_field(char *str, int *outp, unsigned int *maskp, unsigned int max)
   if (!field_defined(str))
     return 1;  // and keep the defaults

+  if (!maskp && str[0] == '0' && (str[1] == 'x' || str[1] == 'X'))
+    str += 2;
+
   while (*str)
     {
       int c = *str++;
```

**Comment by gollux** [comment]
Allowing leading `0x` was never intentional nor documented, but if people rely on it, let's keep it for backward compatibility.
