### ISSUE TITLE
Recover from `Cannot find any working access method`

### ISSUE THREAD

**Issue by CarterLi** [pciutils/pciutils#136]
Ref: https://github.com/LinusDierheimer/fastfetch/issues/433

When libpci fail to init, it prints an error message `Cannot find any working access method` and exits the program.

https://github.com/pciutils/pciutils/blob/bca0412843fa650c749128ade03f35ab3e8fe2b9/lib/init.c#L479

In my case, I want to catch this error and continue my program.  I tried to set access->error to a noop

```c
static void handlePciError(char *msg, ...)
{
// noop
}

void myProgram()
{
    struct pci_access* access = pci_alloc();
    access->error = handlePciError;
    pci_init(access);
    if(!access->methods)
        // handle error
}
```

Got this warning

```
src/detection/gpu/gpu_linux.c:248:23: warning: assignment makes ‘__attribute__((noreturn))’ qualified function pointer from unqualified [-Wdiscarded-qualifiers]
  248 |    access->error = handlePciError;
```

This was bad. AFAIK, returning from a function marked as `noreturn` is an undefined behavior. So I have to touch the SJLJ shit to handle a simple requirement.

Any ideas?

**Comment by CarterLi** [comment]
Can I call `pci_init_internal` directly?

**Comment by gollux** [comment]
> Can I call `pci_init_internal` directly?

No, it's not exported from the library.

The right way is to `longjmp` out of the error handler to your code.

**Comment by gollux** [comment]
Even if we had that, you would have the same problem with all other libpci functions.

Is there any reason why you cannot simply use `longjmp`?

**Comment by CarterLi** [comment]
It's complicated and slow. I just want to handle the initialization, but don't care other places.

**Comment by gollux** [comment]
In case of initialization, you really do not need care about speed of `longjmp`. Initialization will be several orders of magnitude slower.

Why should be `jmp_buf` global? `longjmp` is documented to be thread-safe.

**Comment by CarterLi** [comment]
I don't think `jmp_buf` can be used without declared as a global variable, since it's used in different functions.

**Comment by CarterLi** [comment]
I must say that the error handling of libpci is very unfriendly. Forcing users to use SJLJ is really a bad idea.

**Comment by gollux** [comment]
Refusing to accept that SJ/LJ is the standard mechanism for handling exceptions in C is also a bad idea ;)

Anyway, if you have ideas how to handle errors in libpci better, and you are willing solve more than the rather uninteresting special case of library initialization, patches are welcome.

**Comment by CarterLi** [comment]
> Refusing to accept that SJ/LJ is the standard mechanism for handling exceptions in C is also a bad idea ;)

The fact is that most C users even refuse to accept C++ exceptions. SJLJ is even MUCH worse than C++ exceptions.

> Anyway, if you have ideas how to handle errors in libpci better, and you are willing solve more than the rather uninteresting special case of library initialization, patches are welcome.

All C standard functions use return values ( with `errno`, which I think is bad too ) to handle errors. libpci should be no different.

**Comment by gollux** [comment]
As I said, patches are more welcome than rants.
