### ISSUE TITLE
Long PCI ID causing truncation

### ISSUE THREAD

**Issue by sslupsky** [pciutils/pciutils#139]
There are a few PCI vendor and device names when combined with the device codes (-nn option) causes a string length to exceed the size of the buffer and thus the output is truncated.

For instance,
`Intel Corporation Xeon E7 v2/Xeon E5 v2/Core i7 Integrated Memory Controller 0 Channel Target Address Decoder Registers`

generates the following string:
`0000:ff:0f.2 System peripheral [0880]: Intel Corporation Xeon E7 v2/Xeon E5 v2/Core i7 Integrated Memory Controller 0 Channel Target Address Decoder Registers [808... (rev 04)`

The problem can be fixed by increasing the size of the devbuf here:
https://github.com/pciutils/pciutils/blob/10add64069d23c3fdbff60d537cd8d7e4a5dfa53/lspci.c#L293

**Comment by gollux** [comment]
I enlarged the buffers, but the correct solution is to trim enormous names in the ID database.
