### ISSUE TITLE
pciutils does not follow xdg base directory specification

### ISSUE THREAD

**Issue by pavelskipenes** [pciutils/pciutils#148]
TLDR; save cache file to `$HOME/.cache/pciutils/pciidis` if `$XDG_CACHE_HOME` is not defined otherwise to `$XDG_CACHE_HOME/pciutils/pciidis` instead of `$HOME/.pciids-cache`.

From [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html): 
> The XDG Base Directory Specification is based on the following concepts:
> - There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable `$XDG_CACHE_HOME`.

> `$XDG_CACHE_HOME` defines the base directory relative to which user-specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used. 

Looks like relevant line are around here:
https://github.com/pciutils/pciutils/blob/0766bfa0f557430a6dd3256d45a5b756499f9f7b/lib/init.c#L417

**Comment by gollux** [comment]
Implemented in commit f022f467771c1c4b3270462710923b94b29b3c81.
