### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by reneeotten** [pciutils/pciutils#149]
Thanks for making the software available! We have packaged it in [MacPorts](https://www.macports.org/) as a dependency of `qt6-qtwebengine`. According to the `COPYING` file in your GitHub repository the license is `GPL-2` which causes `qt6-qtwebengine` not to be distributable and thus all our users have to build it locally:
```
./port_binary_distributable.tcl -v qt6-qtwebengine
"qt6-qtwebengine" is not distributable because its license "GPL-3" conflicts with license "GPL-2" of dependency "pciutils"
```

However, the `README` states:
```
All files in this package can be freely distributed and used according
to the terms of the GNU General Public License, either version 2 or
(at your opinion) any newer version. See https://www.gnu.org/ for details.
```

If that is indeed the intention, and we could consider it `GPL-3` that would allow us to distribute binaries of the `qt6-qtwebengine` pacakge. Probably adding to the (or at least our) confusion is that in many of the source files there is the following text in the header: ```Can be freely distributed and used under the terms of the GNU GPL``` without mentioning the version. Our ticket tracking this can be found [here](https://trac.macports.org/ticket/67602).

Can you please comment on this and elaborate on what your licensing terms are?
Thanks!

**Comment by gollux** [comment]
Sorry for the confusion. I updated all license comments to mention "GPL v2+" explicitly and also added SPDX license identifiers to all source files.

Is that OK for you?

**Comment by reneeotten** [comment]
thanks @gollux for the clarification and updates! Perhaps the only other file to updat is COPYING - there should be one that
reflects GPL2+

**Comment by gollux** [comment]
`COPYING` is a verbatim copy of GPL2, which we should not change. There is no official "GPL2+" license we could substitute. Perhaps we can add an introductory paragraph before the license itself, but I do not think it would be better than stating the license terms in the `README`.

**Comment by reneeotten** [comment]
it's fine with me @gollux; this is sufficient notice for is that we can use GPL-2+ - thanks again!

I thought I've come across COPYING files that state something along the lines "or a later version", but perhaps I am misremembering 😉.
