### ISSUE TITLE
Cross compile using mingw-64 for windows 64bit -- failure log

### ISSUE THREAD

**Issue by ralic** [pciutils/pciutils#15]
When I try to compile and port this to windows 64 bit, I find some errors as following.
Is there anything wrong for me to correct for building pciutils for windows 10 64bit ? 

Host OS :
Linux debian9 4.18.0-1-amd64 #1 SMP Debian 4.18.6-1 (2018-09-06) x86_64 GNU/Linux
Source Branch : 
https://github.com/gitGNU/pciutils/tree/windows

install apt packages info :
https://github.com/gitGNU/pciutils/blob/windows/installed_apt.log
make log info : 
https://github.com/gitGNU/pciutils/blob/windows/make.log

```
lib/sysdep.h:27:10: fatal error: asm/byteorder.h: No such file or directory
 #include <asm/byteorder.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by gollux** [comment]
How did you configure libpci?

**Comment by ralic** [comment]
Do you mean the Makefile ? The difference shown as following.
https://github.com/pciutils/pciutils/compare/master...gitGNU:windows?expand=1#diff-b67911656ef5d18c4ae36cb6741b7965

It seems that in the kernel 4.x linux, there is no  asm/byteorder.h. 
asm/byteorder.h is found in kernel v2.6.27 

https://elixir.bootlin.com/linux/v2.6.27/source/arch/arm/include/asm/byteorder.h

**Comment by gollux** [comment]
"Please run the configure script from the top-level Makefile" - that's exactly what you should have done :)

**Comment by ralic** [comment]
I did, the first link was the change I have done. However, it still calls errors. I wonder if it's easy to find an older Linux kernel image may make it easier to compile for windows. Maybe using docker to pull one to support in the compilation could serve as a TODO in the future.

**Comment by gollux** [comment]
Sorry, the Windows port currently lacks a maintainer and I do not have Windows machines to test on (or enough motivation for supporting the Windows port personally). If anybody is interested in taking over maintainership on Windows, you will be welcome.

**Comment by pali** [comment]
Hello @ralic! My pull request https://github.com/pciutils/pciutils/pull/82 is adding basic support for 64-bit windows systems and also updates documentation how to cross compile pciutils for these systems. I have successfully tested it on Debian 10 host system.

**Comment by gollux** [comment]
It is merged to master now.
