### ISSUE TITLE
windows supports DMA access？

### ISSUE THREAD

**Issue by HM281099** [pciutils/pciutils#160]
Platform :windows11

PCIe access modes include DMA mode PIO mode, etc. PIO mode can be accessed through WINIO , but pciutils supports DMA mode？

**Comment by pali** [comment]
I'm not sure that I understand what do you mean by DMA access here. libpci access PCI config space by either CF8/CFC io ports via in/out x86 instructions or by accessing physical ECAM memory mapped to libpci process memory.

**Comment by pali** [comment]
Strictly speaking, libpci does not use any dedicated hardware-DMA for doing transfers of PCI config space to RAM or vice versa.

**Comment by HM281099** [comment]
thank for you reply, best wishes.
