### ISSUE TITLE
3.11.0/3.11.1 released but no tag/tarball.

### ISSUE THREAD

**Issue by milkylainen** [pciutils/pciutils#171]
Hello. Missing tag and no release tarball on github and on kernel.org.

**Comment by gollux** [comment]
I pushed the missing tags (I had a bug in my mirroring scripts, so they didn't get propagated from my private repo tho the public ones), but I don't see any problems with release tarballs at kernel.org. The pciutils never used github for publishing releases.

**Comment by milkylainen** [comment]
Hmm. I checked yesterday. For whatever reason the tarballs weren't there? But it looks like they're three days old. Really weird. I had scripts trying to fetch them but failed.
Oh well. Thanks for fixing, closing.
