### ISSUE TITLE
Better setpci method for basic caps found in lspci like MaxPayload...

### ISSUE THREAD

**Issue by brunogm0** [pciutils/pciutils#179]
Since lspci can find the correct values of many registers and features   WHY setpci dos not replicate those?   and  --dumpregs gives nice info but still  not so easy to use / understand  register nicknames for structs like lspci does.   

  In my case i was trying to increase max payload and max read request.  So lspci gives me current values  but setpci is not so easy to use to configure the same basic PCI info that lspci give me!    

ps.: env Win11, not so easy to find the correct offset for DevCtrl for a AMD GPU.

**Comment by gollux** [comment]
It would be a nice feature, but it would involve a more abstract description of the whole config space parsing process. I would like it, as it would enable structured output (e.g., in JSON as in #61), but it basically requires rewriting the whole lspci, so it's not going to happen anytime soon.

**Comment by gollux** [comment]
Moved to #61.
