### ISSUE TITLE
Problems compiling on Windows

### ISSUE THREAD

**Issue by KevGreenwood** [pciutils/pciutils#185]
Hi, I'm not quite clear what are the requirements to compile pciutils on Windows 11 *(yes, I read the README.Windows but I still don't understand it)*, I tried everything even with MSYS2 but I always get the error that the config.h files are missing in the lib folder.
I'm more interested in compiling lspci for a personal project.
Am I missing some program or requirement that I am overlooking? Thanks.

**Comment by gollux** [comment]
The compilation process we use on Windows is described in `README.Windows`. It uses the MinGW compiler. If you are using Visual Studio instead, you are on your own.
