### ISSUE TITLE
Cannot find libpci.so.3.x after the installation of Pciutils

### ISSUE THREAD

**Issue by Shixiong0** [pciutils/pciutils#186]
Now I'm updating the libpci.so to run the fwts, after the installation of pciutils_3.8.0, I couldn't find the libpci.so.3.8 file in the system, what's the problems?

OS: SLES 15 SP6 GM
Existing pciutils: 3.6.5
Wanted: 3.8.0 or newer

Thanks.

**Comment by gollux** [comment]
Did you compile the pciutils with `SHARED=yes`?

If yes, please share the full output of the build and installation.

**Comment by Shixiong0** [comment]
> Did you compile the pciutils with `SHARED=yes`?
> 
> If yes, please share the full output of the build and installation.

Hi Martin, thanks for your respond.

I didn't find the option "SHARED=yes" when doing the "make", what's the format like?
I tried below format, but it seems not valid:
# make --SHARED=yes
Any suggestion?

Thanks in advance.

**Comment by Shixiong0** [comment]
Hi Martin, thanks for your respond.
I re-installed the pciutils with shared=yes, but seems still cannot find the libpci.so.3.x, could you help to take a look?

Thanks in advance.
[output of installation.txt](https://github.com/user-attachments/files/16126155/output.of.installation.txt)

**Comment by gollux** [comment]
It's `SHARED` in capitals. And if you want to re-compile everything, please do `make clean` first.

**Comment by Shixiong0** [comment]
> It's `SHARED` in capitals. And if you want to re-compile everything, please do `make clean` first.

Hi Martin, I re-compiled it but you know, still cannot find the libpci.so.3.x in system, what else should I do next step？

any suggestion？

Many thanks.

**Comment by Shixiong0** [comment]
Finally, I used sudo to make and make install, the file disappeared:
/root/pciutils-3.11.0/lib/libpci.so.3.11.0

But the user I used is root.. so strange, anyway, thanks for your support, Martin.
