### ISSUE TITLE
Broken link in Windows README

### ISSUE THREAD

**Issue by hjmallon** [pciutils/pciutils#20]
Broken Link: http://www.internals.com/ mentioned in README.Windows

**Comment by JohnAZoidberg** [comment]
Archive.org doesn't seem to carry the DLL but people have created forks/mirrors:
- https://github.com/starofrainnight/winio
- Someone else put it here: https://github.com/vaptu/winio

The binaries of both repos have the same hashes.

**Comment by gollux** [comment]
Fixed, thanks.

Unfortunately, the Windows port still lacks a maintainer. If you know anybody who would be willing to help, please let me know.

**Comment by pali** [comment]
> Archive.org doesn't seem to carry the DLL but people have created forks/mirrors:

Just for the record it is available at this specific archive date:
https://web.archive.org/web/20151005172744/http://www.internals.com/
