### ISSUE TITLE
Is intel-conf1 still reliable when intel_io_lock() is empty?

### ISSUE THREAD

**Issue by AsaMyth** [pciutils/pciutils#27]
https://github.com/pciutils/pciutils/blob/33226851677b92fffd186002d74a1a515fb49413/lib/i386-io-linux.h#L24

This is indeed a question about whether we need a lock for user space application to access IO port. Thanks for reading.
In Linux source arch\x86\pci\direct.c, we saw that the access of IO port is locked by raw_spin_lock_irqsave(). 
`raw_spin_lock_irqsave(&pci_config_lock, flags);`
While in pciutils source:
For the **linux-syfs** method,  the handlers in arch\x86\pci\direct.c are called eventually, thus the accessing is protected by a lock.
For the **intel-conf1** method, there is also a lock function **intel_io_lock()**, but it is empty for most platforms except DOS.

I know that **raw_spin_lock_irqsave()** is not available for Linux user space. Could we say that accessing using intel-conf1 without a locking mechanism is not reliable?

**Comment by gollux** [comment]
Using intel-conf1 is unreliable for a multitude of reasons. There is no
locking either between different processes using libpci, nor between libpci
and the OS. Also, intel-conf1 sees only a subset of existing buses on many
machines. It exists only as the fallback for machines where nothing else works.

**Comment by AsaMyth** [comment]
Hi gollux, thanks for the clear answer.
