### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [pciutils/pciutils#28]
I think that it would be good to flush away all already accumulated patches and make new release :)

**Comment by Neustradamus** [comment]
+1

**Comment by gollux** [comment]
Working on that now, you can expect a new release within a couple of days. Sorry for the long hibernation.

**Comment by Neustradamus** [comment]
@gollux: Thanks for 3.6.3 and 3.6.4!
Please, do not stop to develop it.
