### ISSUE TITLE
Large double BARs with low half equal zero are reported virtual, by lspci show_bases() in verbose header listings

### ISSUE THREAD

**Issue by lc99sj** [pciutils/pciutils#33]
Apology if this has been previously reported.
In the case of large BAR window sizes where the lower half of the BAR is all zero.
I have been noticing for a while that **lspci**, in **verbose** formatted listings of the PCI header,
  these large BARs are always listed as being **virtual**.  Which is not actually the case.
I have a suspicion that the behavior might be due to the expression around
  **lspci.c:426**  , in   **show_bases()**
I mean, at first glance I was thinking that the code might be making this decision solely
  using the low half of the BAR; and it doesn't see whether the upper half is assigned non-zero.
```
  else if (pos && !(flg & ((flg & PCI_BASE_ADDRESS_SPACE_IO) ? PCI_BASE_ADDRESS_IO_MASK : PCI_BASE_ADDRESS_MEM_MASK)))
{
  /* Reported by the OS, but not by the device */
  printf("[virtual] ");
  flg = pos;
  virtual = 1;
}
```
Further details that might be helpful, for description of the issue --
```
root@here:/# setpci -d ::_class_ 14.L
0000000c
0000000c
  ( ... )

root@here:/# setpci -d ::_class_ 18.L
00000640
00000360
  ( ... )

root@here:/# lspci -xs 7:0.0
07:00.0 My Class: My Corporation Device _xx_ (rev a1)
00: xx xx xx xx 06 04 10 00 a1 00 xx xx 10 00 00 00
10: 00 00 00 f8 0c 00 00 00 60 04 00 00 0c 00 00 6e
  ( ... )

root@here:/# cat /sys/bus/pci/devices/0000:07:00.0/resource
0x00000000f8000000 0x00000000f8ffffff 0x0000000000040200
0x0000046000000000 0x0000046_xx_fffff 0x000000000014220c
  ( ... )

root@here:/# grep '07:00' /proc/iomem
          f8000000-f8ffffff : 0000:07:00.0
          46000000000-46_xx_fffff : 0000:07:00.0
            ( ... )

root@here:/# lspci -d ::_class_ -vs 7:
07:00.0 My Class: My Corporation Device _xx_ (rev a1)
        Subsystem: My Corporation Device _yy_
        Flags: bus master, fast devsel, latency 0, IRQ 62, NUMA node 0
        Memory at f8000000 (32-bit, non-prefetchable) [size=16M]
        [virtual] Memory at 46000000000 (64-bit, prefetchable) [size=_some_G]
  ( ... )

root@here:/# lspci -vvd ::_class_ | grep -i "^[       ]region 1"
        Region 1: [virtual] Memory at 46000000000 (64-bit, prefetchable) [size=_some_G]
        Region 1: [virtual] Memory at 44000000000 (64-bit, prefetchable) [size=_some_G]
          ( ... )

root@here:/# lspci --version
lspci version 3.6.2
root@here:/# setpci --version
setpci version 3.6.2

root@here:/# lsb_release -a
LSB Version:    core-11.0.1ubuntu1-noarch:security-11.0.1ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

root@here:/# dpkg -l pciutils
  ( ... )
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  pciutils       1:3.6.2-2    amd64        PCI utilities
```

**Comment by gollux** [comment]
This is obviously wrong and the code which prints the addresses has evolved to something so messy, that it is not easy to fix this problem. So I rewrote it to something cleaner and more maintainable. Could you please check the current master?

**Comment by lc99sj** [comment]
Oh, wow, awesome ... I will try to get that tested this afternoon, will post back here.  Thank you.

**Comment by lc99sj** [comment]
I didn't expect to get the following result --
Building the current **master** ( which reports that it's version **3.6.4** ) I don't see the  **[virtual]**  failure.
But I'm also not seeing that failure, when I run on hosts that have utilities version **3.5.2**
  which is from  pciutils 1:3.5.2-1ubuntu1.1  in  Ubuntu 18.04.3 LTS.
I just tested the current  **master**  on these hosts; so that, not seeing any failure
  under any condition, here, didn't validate the case.

I need to do one or two things, here.  First off, go back to a host that matches what I had
  posted, initially ( Ubuntu 19.10, etc. ) and see whether the new code works properly,
  while the  **3.6.2** package does not.
Secondly, on these other ( Ubuntu 18.04.3 / pciutils 3.5.2 ) hosts, see whether any other
  pciutils version can produce the failure described.  The older code should consistently give
  the same result, according to the Function's BAR register values.
I need to get a handle on what is going on, here.

**Comment by gollux** [comment]
Do you still see zeroes in the lower 32 bits of region addresses?

**Comment by lc99sj** [comment]
Yes, absolutely ... that ( lower half being all zero, aside from the flags ) hasn't changed.
I'm planning to clear up the above; meaning testing on different versions,
  and finding out why the problem here has gone away.
I'll append back once I get the testing completed.  Thanks.

**Comment by gollux** [comment]
Detection of virtual regions underwent significant changes in the current master, so it is worth re-checking if the problem persists.

**Comment by gollux** [comment]
I am closing this issue. If you are able to reproduce the problem with current pciutils, feel free to re-open.
