### ISSUE TITLE
setpci fails when adding/removing unrelated devices

### ISSUE THREAD

**Issue by mlnx-avivb** [pciutils/pciutils#34]
trying to setpci on device A (in this example: 0000:81:00.0)
setpci -A linux-sysfs -s 81:00.0 0.L

adding/removing unrelated devices will cause the setpci to fail. 
for example, when adding and removing SRIOV devices on device B (commands in a loop for fast repro):
[root@localhost]$ for i in {0..99} ; do for j in 6 0 ; do echo $j > /sys/bus/pci/devices/0000\:82\:00.0/sriov_numvfs ; done ; done

[root@localhost]$ i=0 ; while [ 1 ] ; do echo -n "i=$i ; " ; setpci -A linux-sysfs -s 81:00.0 0.L ; if [ $? -ne 0 ] ; then break ; fi ; let i+=1 ; done
setpci on device A failing on the unrelated device B:
setpci: Cannot open /sys/bus/pci/devices/0000:82:00.5/resource: No such file or directory

**Comment by gollux** [comment]
Interesting... so far, we assumed that sysfs does not change during
a bus scan, which was obviously naive :)

First of all, I changed setpci to avoid the bus scan if you select
a specific device (however, you need to specify the domain number,
too, because the default domain for -s is "any"). Could you try the
current master, please?

I will also modify the sysfs back-end to be more lenient to
scanning errors.

**Comment by mlnx-avivb** [comment]
many thanks for the prompt reply..
i tried adding the domain and rerunning over the master with your new commit but no luck, still fails on the changed sysfs.

new command:
i=0 ; while [ 1 ] ; do echo -n "i=$i ; " ; sudo ./setpci -s **0000:**81:00.0 0.L ; if [ $? -ne 0 ] ; then break ; fi ; let i+=1 ; done

let me know if there's anything else you want to test (or if i'm missing something from the command)
re being more tolerant to sysfs changes - that would have been my next request..

thanks.

**Comment by gollux** [comment]
> let me know if there's anything else you want to test (or if i'm missing something from the command)

Please add the new "-r" switch, too. (Sorry, I forgot to tell you...)

**Comment by mlnx-avivb** [comment]
great, not failing anymore!
