### ISSUE TITLE
pci utils for windows with winio.dll

### ISSUE THREAD

**Issue by liujian883** [pciutils/pciutils#36]
hello
I downloaded pciutils_win64 from https://eternallybored.org/misc/pciutils and found a DirectIOLibx64.dll inside. but I see pciutils source code said the winio.dll needed, also need to install a unsigned kernel driver.
Is the directiolibx64.dll provided a substitute for winio.dll? Where can I download or get the source code, or where can I get more information about it?
Thank you !

**Comment by pali** [comment]
Hello @liujian883! Now pciutils in git master branch do not require winio.dll nor any kernel driver.
