### ISSUE TITLE
lspci -mm -k doesn't print kernel modules

### ISSUE THREAD

**Issue by cslycord** [pciutils/pciutils#37]
In machine-readable mode, kernel modules aren't output when -k is specified
lspci -mm and lspci -mm -k produce identical output that doesn't contain the kernel modules used

I've provided output run inside a gentoo qemu VM, with pciutils version 3.6.4
`tux ~/helper # lspci -mm
00:00.0 "Host bridge" "Intel Corporation" "440FX - 82441FX PMC [Natoma]" -r02 "Red Hat, Inc." "Qemu virtual machine"
00:01.0 "ISA bridge" "Intel Corporation" "82371SB PIIX3 ISA [Natoma/Triton II]" "Red Hat, Inc." "Qemu virtual machine"
00:01.1 "IDE interface" "Intel Corporation" "82371SB PIIX3 IDE [Natoma/Triton II]" -p80 "Red Hat, Inc." "Qemu virtual machine"
00:01.3 "Bridge" "Intel Corporation" "82371AB/EB/MB PIIX4 ACPI" -r03 "Red Hat, Inc." "Qemu virtual machine"
00:02.0 "VGA compatible controller" "Vendor 1234" "Device 1111" -r02 "Red Hat, Inc." "Device 1100"
00:03.0 "Ethernet controller" "Red Hat, Inc." "Virtio network device" "Red Hat, Inc." "Virtio network device"
00:04.0 "SCSI storage controller" "Red Hat, Inc." "Virtio SCSI" "Red Hat, Inc." "Virtio SCSI"
00:05.0 "Unclassified device [00ff]" "Red Hat, Inc." "Virtio RNG" "Red Hat, Inc." "Virtio RNG"`

`tux ~/helper # lspci -mm -k
00:00.0 "Host bridge" "Intel Corporation" "440FX - 82441FX PMC [Natoma]" -r02 "Red Hat, Inc." "Qemu virtual machine"
00:01.0 "ISA bridge" "Intel Corporation" "82371SB PIIX3 ISA [Natoma/Triton II]" "Red Hat, Inc." "Qemu virtual machine"
00:01.1 "IDE interface" "Intel Corporation" "82371SB PIIX3 IDE [Natoma/Triton II]" -p80 "Red Hat, Inc." "Qemu virtual machine"
00:01.3 "Bridge" "Intel Corporation" "82371AB/EB/MB PIIX4 ACPI" -r03 "Red Hat, Inc." "Qemu virtual machine"
00:02.0 "VGA compatible controller" "Vendor 1234" "Device 1111" -r02 "Red Hat, Inc." "Device 1100"
00:03.0 "Ethernet controller" "Red Hat, Inc." "Virtio network device" "Red Hat, Inc." "Virtio network device"
00:04.0 "SCSI storage controller" "Red Hat, Inc." "Virtio SCSI" "Red Hat, Inc." "Virtio SCSI"
00:05.0 "Unclassified device [00ff]" "Red Hat, Inc." "Virtio RNG" "Red Hat, Inc." "Virtio RNG"`

`tux ~/helper # lspci -k
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
        Subsystem: Red Hat, Inc. Qemu virtual machine
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
        Subsystem: Red Hat, Inc. Qemu virtual machine
00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]
        Subsystem: Red Hat, Inc. Qemu virtual machine
        Kernel driver in use: ata_piix
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
        Subsystem: Red Hat, Inc. Qemu virtual machine
00:02.0 VGA compatible controller: Device 1234:1111 (rev 02)
        Subsystem: Red Hat, Inc. Device 1100
00:03.0 Ethernet controller: Red Hat, Inc. Virtio network device
        Subsystem: Red Hat, Inc. Virtio network device
        Kernel driver in use: virtio-pci
00:04.0 SCSI storage controller: Red Hat, Inc. Virtio SCSI
        Subsystem: Red Hat, Inc. Virtio SCSI
        Kernel driver in use: virtio-pci
00:05.0 Unclassified device [00ff]: Red Hat, Inc. Virtio RNG
        Subsystem: Red Hat, Inc. Virtio RNG
        Kernel driver in use: virtio-pci`

**Comment by gollux** [comment]
Kernel drivers are not used in the basic machine-readable format. Use "lspci -vmm" to get them.
