### ISSUE TITLE
Use PCI_EXP_LNKCAP2 for PCIe r3.0 devices

### ISSUE THREAD

**Issue by khfeng** [pciutils/pciutils#38]
We are seeing different Thunderbolt downstream port speed between kernel and lspci. It turns out to be lspci uses PCI_EXP_LNKCAP, while kernel uses PCI_EXP_LNKCAP2 to determine the speed cap [1]. Quote the comment in pcie_get_speed_cap():
        /*
         * Link Capabilities 2 was added in PCIe r3.0, sec 7.8.18.  The
         * implementation note there recommends using the Supported Link
         * Speeds Vector in Link Capabilities 2 when supported.
         *
         * Without Link Capabilities 2, i.e., prior to PCIe r3.0, software
         * should use the Supported Link Speeds field in Link Capabilities,
         * where only 2.5 GT/s and 5.0 GT/s speeds were defined.
         */     
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/pci/pci.c#n5773

**Comment by gollux** [comment]
We should decode LNKCAP2, too. See commit 623ed0e1afa959013f4d7e507dd12cb9e4811577.
