### ISSUE TITLE
size=nn[KMG] missing when using -vvvv from -F dump file

### ISSUE THREAD

**Issue by Nicholas-Johnson-opensource** [pciutils/pciutils#41]
Hello again,

When using the file produced from "lspci -xxxx" command with "lspci -F file -vvvv", the size of memory is not printed as it would when simply doing "lspci -vvvv" on the same system.

Notice how the following two commands differ:
$ lspci -vvvv | grep Region....Memory
$ lspci -xxxx | lspci -F /dev/stdin -vvvv | grep Region....Memory

The first line of the first command:
Region 0: Memory at db000000 (64-bit, non-prefetchable) [size=16M]

The first line of the second command:
Region 0: Memory at db000000 (64-bit, non-prefetchable)

When using the dump of the mmconfig from the file, we are missing the size at the end, which makes looking at dumps much more difficult when you care about the size.

Is this something you are willing to fix?

Thank you!

**Comment by gollux** [comment]
The dump simply does not contain information about region sizes. The only way how to obtain region size is to actively check which bits of the particular base address register can be modified and which are hard-wired to 0. This obviously cannot be done with a dump.
