### ISSUE TITLE
FreeBSD11.4 no device and vender name print

### ISSUE THREAD

**Issue by ChancelScholar** [pciutils/pciutils#45]
FreeBSD11.4 no device and vender name print,only print Device venderId:deviceId.like:
```00:00.0 Class 0600: Device 8086:7190 (rev 01)
00:01.0 Class 0604: Device 8086:7191 (rev 01)
00:07.0 Class 0601: Device 8086:7110 (rev 08)
00:07.1 Class 0101: Device 8086:7111 (rev 01)
00:07.3 Class 0680: Device 8086:7113 (rev 08)
00:07.7 Class 0880: Device 15ad:0740 (rev 10)
```
It has pci.ids table here.

**Comment by gollux** [comment]
Is the pci.ids file at the proper place? Does specifying the location of pci.ids using the `-i` switch help?

**Comment by gollux** [comment]
This waits for feedback for more than one year, so I am closing it.
