### ISSUE TITLE
Ubuntu Linux 20.04 LTS using  version 3.6.4 Memory Leak

### ISSUE THREAD

**Issue by lfranken7** [pciutils/pciutils#52]
I've been using this utility with Linux for some time and I think I've found a memory leak using Valgrind on the example.c program. I think the pci_cleanup(...) command doesn't fully free all memory used by the pci_alloc(...) pci_init(...) and pci_scan_bus(...). Valgrind points to memory allocated with pci_scan_bus(...). 

The output of valgrind is as follows:

[vg_out.txt](https://github.com/pciutils/pciutils/files/5539260/vg_out.txt)

**Comment by gollux** [comment]
I hope I fixed the leak, could you please test with current master branch?
