### ISSUE TITLE
lspci -vv or -vvv through a pipe outputs errors in stderr

### ISSUE THREAD

**Issue by NVieville** [pciutils/pciutils#55]
Hello,

lspci version 3.6.4 on Fedora 33 x86_64 with GNU/Linux kernel 5.10.4-200.fc33.x86_64

Trying the command below in a root console prints an error through stderr:

lspci -vvv | grep -i vga
[...]
pcilib: sysfs_read_vpd: read failed: Input/output error
[...]

The same command with -v outputs no error.
The same command with -vv outputs the same error.

Removing the pipe to grep for the 3 variants of the -v commutator (-v, -vv, -vvv) outputs no errors.
Seems that piping lspci with double or triple -v commutator produces the stderr message.

Hope this description will help.

Feel free to make any comment.

Cordially,

-- 
NVieville

**Comment by gollux** [comment]
Piping does not change anything except for order of buffer flushes, so the errors are probably just displayed somewhere else.

**Comment by NVieville** [comment]
Hello,

Thanks for your reply.

Here, eleven months later, with lspci version 3.7.0 on Fedora 35 x86_64 with GNU/Linux kernel 5.15.10-200.fc35.x86_64, no problem any more.
For your information, the outputs of  the lspci commands of the first message were all checked manually (in gnome terminal and using search tool) and no errors were displayed elsewhere, sorry.

Cordially,


-- 

NVieville
