### ISSUE TITLE
sigsegv error in sysfs.c

### ISSUE THREAD

**Issue by dreamtale90** [pciutils/pciutils#60]
Hello, I have a crash problem today. The call stack is as follows:
pci_scan_bus -> sysfs_scan -> sysfs_get_resources -> fgets(fp = 0x0)
So, after fopen fails, should it return directly?

version: pciutils-3.6.4

**Comment by gollux** [comment]
Does this happen when running `lspci`? Or another program linked with `libpci`?

**Comment by dreamtale90** [comment]
@gollux My program is linked with libpci library. Finally, it was found that the real problem was that another module had a file handle leak. It just happens that this location of libpci crashes when it is used directly without checking the return result after calling fopen. However, for safety reasons, inspections should be added in similar situations.

**Comment by gollux** [comment]
I suspect that your program implements the `error` hook incorrectly. The error hook must never return - it must either exit the program or leave via `longjmp` or another kind of non-local jump (e.g., a C++ exception).

**Comment by pali** [comment]
> I suspect that your program implements the `error` hook incorrectly. The error hook must never return

I did same mistake too...

What about following change to explicitly mark that `error` hook should not return? I'm not sure if compilers are smart enough to detect that noreturn-decorated hook returns but big uppercase attribute before function name could help human readers a little bit.

```diff
diff --git a/lib/pci.h b/lib/pci.h
index 4a2dfbcb2327..409c03c8753c 100644
--- a/lib/pci.h
+++ b/lib/pci.h
@@ -63,7 +63,7 @@ struct pci_access {
   int debugging;			/* Turn on debugging messages */
 
   /* Functions you can override: */
-  void (*error)(char *msg, ...) PCI_PRINTF(1,2);	/* Write error message and quit */
+  PCI_NONRET void (*error)(char *msg, ...) PCI_PRINTF(1,2);	/* Write error message and quit */
   void (*warning)(char *msg, ...) PCI_PRINTF(1,2);	/* Write a warning message */
   void (*debug)(char *msg, ...) PCI_PRINTF(1,2);	/* Write a debugging message */
 
diff --git a/lib/types.h b/lib/types.h
index 2b4d4e1a3dd7..c2f4f2fa4d71 100644
--- a/lib/types.h
+++ b/lib/types.h
@@ -74,6 +74,8 @@ typedef u32 pciaddr_t;
 
 #if defined(__GNUC__) && __GNUC__ > 2
 #define PCI_PRINTF(x,y) __attribute__((format(printf, x, y)))
+#define PCI_NONRET __attribute__((noreturn))
 #else
 #define PCI_PRINTF(x,y)
+#define PCI_NONRET
 #endif
```

**Comment by dreamtale90** [comment]
Thank you for your reply. I'm sorry that I really don't implement the callback function of error handling here. @gollux @pali

**Comment by gollux** [comment]
@pali, I like this idea. Implemented in master.
