### ISSUE TITLE
Enhance class selector

### ISSUE THREAD

**Issue by rowlap** [pciutils/pciutils#66]
Currently filtering with `-d` allows selection of vendor:device:class, but the class field is really "Class Code + Sub-Class Code", looking at the PCI spec.

In the case where, for example, we'd like to detect all mass storage controllers (of any type), this isn't currently possible
```
# lspci -n -d ::0104
18:00.0 0104: 1000:0016 (rev 01)

# lspci -n -d ::01
[no output]
```
As it doesn't seem particularly useful to filter *only* on subclass, could the syntax above be acceptable to `pci_filter_parse_id()`?

**Comment by gollux** [comment]
It is supported as `::01xx` by the current master. I also added matching of the programming interface.

**Comment by rowlap** [comment]
For completeness, linking to 511122b83c127487f3aa1d27c7a5977d033454e2 / 2c32712a1b78818c4d3fd6dc814bc505ba78f52c / 21c4801a4f26764d1df323afd1f61b6f7b65013d.
