### ISSUE TITLE
Received a warning while cloning in Cygwin: "warning: the following paths have collided"

### ISSUE THREAD

**Issue by rcn5440** [pciutils/pciutils#67]
Today I cloned the repo in Cygwin and received the following warning. Hopefully this will be an easy fix.

> warning: the following paths have collided (e.g. case-sensitive paths
> on a case-insensitive filesystem) and only one from the same
> colliding group is in the working tree:
> 
>   'maint/RELEASE'
>   'maint/release'
> 

Only the "release" file was present in my working tree.

**Comment by gollux** [comment]
Ah, those case-insensitive filesystems. But if we want to pretend we are supporting Windows, we should avoid collisions of this kind... Fixed.
