### ISSUE TITLE
lspci bus mapping for non-zero domains

### ISSUE THREAD

**Issue by pali** [pciutils/pciutils#85]
Trying to show device 1:1:1.0 via lspci bus mapping mode with arguments `-G -M -s 1:1:1.0` shows very strange message that device was discovered but then filtered out even that it was explicitly set to not filter it via `-s`:

```
Mapping bus 01
Discovered device 01:01.0
But it was filtered out.

Summary of buses:

01: Secondary host bus (?)
```

Currently in lspci manpage is documented that bus mapping works only for devices at domain 0, but from above message it is not obvious.

So it would be nice to add support for bus mapping mode also for non-zero domains OR at least improve that lspci output message...

**Comment by gollux** [comment]
It's a good idea. Can you check with the current master, please?

**Comment by pali** [comment]
Perfect, it is working fine now! With arguments ` -G -M -s 2:3:0.0 -nn` I'm getting:
```
Mapping bus 0002:03
Discovered device 0002:03:00.0
0002:03:00.0 Network controller [0280]: Qualcomm Atheros AR9287 Wireless Network Adapter (PCI-Express) [168c:002e] (rev 01)

Summary of buses:

03: Secondary host bus (?)
```
