### ISSUE TITLE
lspci: Inconsistency in Region X: lines

### ISSUE THREAD

**Issue by pali** [pciutils/pciutils#90]
I have not found documentation with explanation of the meaning of `Region X:` lspci lines.

What kind of address should these lines contain?

Because for I/O ports there are at least 3 different type of  addresses which belong to one I/O port mapping region:
* PCI bus address
* physical CPU address
* remapped CPU address

Probably on x86 systems they are same but e.g. on arm64 system they can be different.

Here is the output from Linux arm64 system on which PCI bus address = physical CPU address = 0xe8000000 and remapped CPU address = 0x0 for SATA controller add-on PCIe card which uses I/O ports. Output is different when called with and without -b.

```
lspci -vv
        Region 0: I/O ports at 1020 [size=8]
        Region 1: I/O ports at 1030 [size=4]
        Region 2: I/O ports at 1028 [size=8]
        Region 3: I/O ports at 1034 [size=4]
        Region 4: I/O ports at 1000 [size=32]
        Region 5: Memory at e9010000 (32-bit, non-prefetchable) [size=512]
```

```
lspci -vv -b
        Region 0: I/O ports at e8001020
        Region 1: I/O ports at e8001030
        Region 2: I/O ports at e8001028
        Region 3: I/O ports at e8001034
        Region 4: I/O ports at e8001000
        Region 5: Memory at e9010000 (32-bit, non-prefetchable)
```

Which means that lspci without -b prints different address type than with -b. It is expected behavior?

Should lspci without -b really prints remapped CPU address which is not used neither by PCI HW nor by CPU itself?

If yes, this should be documented, what lspci output means. If not, it should be fixed so same type of address is printed with or without -b.

In card resource file is this content:
```
/sys/bus/pci/devices/0000:03:00.0/resource
0x0000000000001020 0x0000000000001027 0x0000000000040101
0x0000000000001030 0x0000000000001033 0x0000000000040101
0x0000000000001028 0x000000000000102f 0x0000000000040101
0x0000000000001034 0x0000000000001037 0x0000000000040101
0x0000000000001000 0x000000000000101f 0x0000000000040101
0x00000000e9010000 0x00000000e90101ff 0x0000000000040200
0x00000000e9000000 0x00000000e900ffff 0x0000000000046200
```

In PCI config space this content:
```
03:00.0 
00: 21 1b 12 06 07 04 10 00 02 01 06 01 00 00 00 00
10: 21 10 00 e8 31 10 00 e8 29 10 00 e8 35 10 00 e8
20: 01 10 00 e8 00 00 01 e9 00 00 00 00 21 1b 60 10
30: 00 00 00 00 50 00 00 00 00 00 00 00 3a 01 00 00
```

And relevant lines from /proc/ioports and /proc/iomem:
```
/proc/ioports
00000000-00ffffff : pcie@d0070000
  00001000-00002fff : PCI Bus 0000:01
    00001000-00001fff : PCI Bus 0000:02
      00001000-00001fff : PCI Bus 0000:03
        00001000-0000101f : 0000:03:00.0
          00001000-0000101f : ahci
        00001020-00001027 : 0000:03:00.0
          00001020-00001027 : ahci
        00001028-0000102f : 0000:03:00.0
          00001028-0000102f : ahci
        00001030-00001033 : 0000:03:00.0
          00001030-00001033 : ahci
        00001034-00001037 : 0000:03:00.0
          00001034-00001037 : ahci
```
```
/proc/iomem
e9000000-efffffff : pcie@d0070000
  e9000000-e91fffff : PCI Bus 0000:01
    e9000000-e91fffff : PCI Bus 0000:02
      e9000000-e90fffff : PCI Bus 0000:03
        e9000000-e900ffff : 0000:03:00.0
        e9010000-e90101ff : 0000:03:00.0
          e9010000-e90101ff : ahci
```

On other arm64 setup where even PCI bus address and physical CPU address are different I verified that lspci with -b prints really PCI bus address.

**Comment by gollux** [comment]
`lspci -b` reports addresses as written in configuration registers of the device. Without `-b`, it prints the addresses reported by the kernel, whose semantics is architecture-specific.
