### ISSUE TITLE
How does lspci find out physical slot number of a PCI(E) device?

### ISSUE THREAD

**Issue by Prandr** [pciutils/pciutils#92]
Hello, this is not a problem with pciutils, but rather another "help wanted" question, which, however, I hope wouldn't be too burdensome to answer for the who involved in  lspci development and know it in depth.

`lspci ` is capable to show physical slot number in the verbose presentation:
![B48Kc](https://user-images.githubusercontent.com/12192141/155961486-3fe1ff0a-47da-4a50-b82f-6cbde311fa0a.png)

I'd like to find out how it does it. I am going to apply this method in the driver that I would like to modify, so it would enumerate the devices (with the same ID) and disambiguate the device files according to physical slot. Like /dev/device__physslot_ . The driver will run on Ubuntu 18

I tried to dig in the source code. I found the relevant line 775 in https://github.com/pciutils/pciutils/blob/master/lspci.c :

```
if (p->phy_slot)
    printf("\tPhysical Slot: %s\n", p->phy_slot);
```
p is struct pci_dev. That had been quite confusing because standard linux/pci.h does not have field phy_slot until I figured out that is [their own (re)definition](https://github.com/pciutils/pciutils/blob/master/lib/pci.h)

The structure [is filled](https://github.com/pciutils/pciutils/blob/master/lib/access.c) by the function

```
int
pci_fill_info_v38(struct pci_dev *d, int flags)
{
  unsigned int uflags = flags;
  if (uflags & PCI_FILL_RESCAN)
    {
      uflags &= ~PCI_FILL_RESCAN;
      pci_reset_properties(d);
    }
  if (uflags & ~d->known_fields)
    d->methods->fill_info(d, uflags);
  return d->known_fields;
}
```
fill_info is a function pointer defined in https://github.com/pciutils/pciutils/blob/master/lib/internal.h (line 44)

And that's where I lost track.

So I am interested in code that could retrieve the physical slot number on  Ubuntu 18

**Comment by gollux** [comment]
`lspci` simply prints what's reported by the kernel in sysfs.

**Comment by Prandr** [comment]
I found the answer after running lspci in the debugger:
it uses /sys/bus/pci/slots/_slot_num_/address files to attribute slot to a bus address.
Unfortunately it turned out to be unsuitable for my purposes, but thanks anyway for the answer.
