### ISSUE TITLE
pciutils: Two questions abort code

### ISSUE THREAD

**Issue by hifilove** [pciutils/pciutils#93]
Hi Martin Mares,
I have two questions for you：
What is the purpose of the files in the "tests" folder?
Does the community have test cases?
Many thanks for your continuing work on pciutils.

**Comment by gollux** [comment]
There is no automated testing, we only have a collection of configuration space dumps exhibiting various intersting cases (e.g., less commonly used capabilities).

**Comment by hifi521** [comment]
Thank you for your reply, which is very useful to me.
